Moo\FlashCardBundle\Entity\CardView:
    type: entity
    repositoryClass: Moo\FlashCardBundle\Repository\CardView
    table: card_view
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        timestamp:
            type: datetime
            nullable: false
        ip:
            type: integer
            unsigned: false
            nullable: false
    manyToOne:
        card:
            targetEntity: Card
            cascade: {  }
            mappedBy: null
            inversedBy: cardViews
            joinColumns:
                card_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
    options:
      collate: utf8_unicode_ci
      charset: utf8
    indexes:
      ipcard:
        columns: [ip, card_id]
