Moo\FlashCardBundle\Entity\Card:
    type: entity
    repositoryClass: Moo\FlashCardBundle\Repository\Card
    table: card
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        slug:
            type: string
            length: 100
            fixed: false
            nullable: false
            gedmo:
              slug:
                separator: -
                style: default
                fields:
                  - title
        isActive:
            type: boolean
            nullable: true
            column: is_active
            default: false
        title:
            type: string
            length: 255
            fixed: false
            nullable: false
        content:
            type: text
            nullable: false
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false
        metaKeywords:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: meta_keywords
        metaDescription:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: meta_description
        views:
            type: integer
            unsigned: false
            nullable: false
            default: 0
    oneToMany:
        cardViews:
            targetEntity: CardView
            mappedBy: card
    manyToOne:
        category:
            targetEntity: Category
            cascade: {  }
            mappedBy: null
            inversedBy: cards
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
    options:
      collate: utf8_unicode_ci
      charset: utf8
    indexes:
      slug:
        columns: [slug]
        type: unique
      title:
        columns: [title]
