# services to handle doctrine extensions
services:
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

# application general configuration
parameters:
    flashcard.app.version: 1.0.2
    flashcard.app.name: "Moo FlashCard"

# Twig Configuration
twig:
    exception_controller: "moo_flashcard.exception.controller:showAction"
    globals:
        flashcard_name: %flashcard.app.name%
        flashcard_version: %flashcard.app.version%
assetic:
    bundles:        ['MooFlashCardBundle']

# FOS rest
fos_rest:
    param_fetcher_listener: force
    routing_loader:
        default_format: json
    view:
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
        force_redirects:
            html: true
        formats:
            json: true
            xml: false
            rss: false
        templating_formats:
            html: true
framework:
    validation: { enable_annotations: true }

nelmio_api_doc:
    name: %flashcard.app.name% API documentation
