language: php

php:
  - 5.3

env:
  - SYMFONY_VERSION=2.3.*

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-source
  - composer install --dev --prefer-source

script: phpunit --coverage-text

