language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist
  - composer install --prefer-dist

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

